name: Deploy Express Backend to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy code and restart server
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_PROJECT_DIR: ${{ secrets.EC2_PROJECT_DIR }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          ssh $EC2_USER@$EC2_HOST << EOF
            # Install Node, Git, PM2 if missing
            command -v git >/dev/null 2>&1 || sudo yum install -y git
            command -v node >/dev/null 2>&1 || curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash - && sudo yum install -y nodejs
            command -v pm2 >/dev/null 2>&1 || sudo npm install -g pm2

            # Clone if missing, else pull
            if [ ! -d "$EC2_PROJECT_DIR" ]; then
              git clone https://github.com/mohitchauhan13/File-upload-API.git "$EC2_PROJECT_DIR"
            fi

            cd "$EC2_PROJECT_DIR"
            git pull origin main

            # Write .env file
            echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" > .env
            echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
            echo "AWS_REGION=$AWS_REGION" >> .env
            echo "S3_BUCKET_NAME=$S3_BUCKET_NAME" >> .env

            npm install

            # Start or restart server
            pm2 start server.js --name backend --update-env || pm2 restart backend
          EOF
